services:
  app:
    build: .
    depends_on:
      - db
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    command: [ "sh", "-c", "npx prisma migrate deploy && npm run start:prod" ]
    deploy:
      resources:
        limits:
          cpus: "1.0" # Limita a 1 vCPU
          memory: "512M" # Limita a 512MB de RAM
        reservations:
          cpus: "0.5" # Reserva 0.5 vCPU
          memory: "256M" # Reserva 256MB de RAM

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
